### ISSUE TITLE
Don't use 'inherit' in sub-classes

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-nscd#15]
This isn't considered good practice.
See https://docs.puppet.com/puppet/4.10/lang_classes.html#inheritance

**Comment by traylenator** [comment]
So I normally assume puppetlabs-ntp is the golden example of practice and it still uses them.

Not really sure what to do in the template? Use full paths?

**Comment by alexjfisher** [comment]
I've been told that about puppetlabs ntp.  But in this case, it seems to directly contradict the style guide (which had a big puppet 4 refresh fairly recently)

https://docs.puppet.com/puppet/4.10/style_guide.html#class-inheritance
>Class inheritance should not be used. Use data binding instead of params.pp pattern. Inheritance should only be used for params.pp, which is not recommended in Puppet 4.

Are all the subclasses 'private' (ie only ever meant to be included from init.pp)?  In which case, what does inherits [here](https://github.com/voxpupuli/puppet-nscd/blob/d0acd040c1c29e0e43819759e9b1d6812ef99a2d/manifests/service.pp#L6) actually do?

**Comment by traylenator** [comment]
It allows you to use short variable names in the templates.

**Comment by alexjfisher** [comment]
I meant specifically in service.pp.  Anyway, let's leave things as they are for now.  Even the styleguide seems a bit confused.  Having said not to use class inheritance, it then features in the 'good' examples section...
