### ISSUE TITLE
The module should allow all global and per-service properties to be managed

### ISSUE THREAD

**Issue by jcbollinger** [voxpupuli/puppet-nscd#40]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: all
- Ruby: all
- Distribution: all
- Module version: 1.0.0

## What are you seeing
The module supports customization of only a few of nscd's configuration properties.  All others are assigned hardcoded values.

## What behaviour did you expect instead
The module should provide means to manage substantially all nscd configuration properties -- both global and service-specific -- to user-chosen values.

**Comment by grbailey66** [comment]
Just want to add that I agree.  I have need to manage other NSCD parameters than what are covered here.

**Comment by traylenator** [comment]
Sure just hoping to get #31 in before adding more configurations.
